// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLd7gLIlFfqjJLmtPQoj6VJYz_Ak_DQuk',
    appId: '1:788470607280:web:9c0b4fa1dde49ff5797a75',
    messagingSenderId: '788470607280',
    projectId: 'e-commerce-app-11f78',
    authDomain: 'e-commerce-app-11f78.firebaseapp.com',
    storageBucket: 'e-commerce-app-11f78.appspot.com',
    measurementId: 'G-MHM6B7VJGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDKfvw9C4TxrINtEwMXhx9_-HM0RsCLHw',
    appId: '1:788470607280:android:e2098ea3b09d2637797a75',
    messagingSenderId: '788470607280',
    projectId: 'e-commerce-app-11f78',
    storageBucket: 'e-commerce-app-11f78.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANrRZsOYuDbkWiGhhlnzEy7_pvEBYifHg',
    appId: '1:788470607280:ios:6e2a7388b1871892797a75',
    messagingSenderId: '788470607280',
    projectId: 'e-commerce-app-11f78',
    storageBucket: 'e-commerce-app-11f78.appspot.com',
    iosBundleId: 'com.example.khyberChat',
  );
}
